// Type mapping for different languages
const TYPE_MAPPINGS = {
  java: {
    'int': 'int',
    'long': 'long',
    'float': 'float',
    'double': 'double',
    'bool': 'boolean',
    'string': 'String',
    'int[]': 'int[]',
    'long[]': 'long[]',
    'float[]': 'float[]',
    'double[]': 'double[]',
    'bool[]': 'boolean[]',
    'string[]': 'String[]',
    'List<int>': 'List<Integer>',
    'List<long>': 'List<Long>',
    'List<float>': 'List<Float>',
    'List<double>': 'List<Double>',
    'List<bool>': 'List<Boolean>',
    'List<string>': 'List<String>',
    'List<int[]>': 'List<int[]>',
    'List<List<int>>': 'List<List<Integer>>',
    'Tree<int>': 'TreeNode',
    'Tree<string>': 'TreeNode',
    'Graph': 'int[][]'
  },
  python: {
    'int': 'int',
    'long': 'int',
    'float': 'float',
    'double': 'float',
    'bool': 'bool',
    'string': 'str',
    'int[]': 'List[int]',
    'long[]': 'List[int]',
    'float[]': 'List[float]',
    'double[]': 'List[float]',
    'bool[]': 'List[bool]',
    'string[]': 'List[str]',
    'List<int>': 'List[int]',
    'List<long>': 'List[int]',
    'List<float>': 'List[float]',
    'List<double>': 'List[float]',
    'List<bool>': 'List[bool]',
    'List<string>': 'List[str]',
    'List<int[]>': 'List[List[int]]',
    'List<List<int>>': 'List[List[int]]',
    'Tree<int>': 'Optional[TreeNode]',
    'Tree<string>': 'Optional[TreeNode]',
    'Graph': 'List[List[int]]',
    'Tuple<int, int>': 'Tuple[int, int]',
    'Tuple<int, string>': 'Tuple[int, str]',
    'Tuple<string, string>': 'Tuple[str, str]',
    'Tuple[string, int]': 'Tuple[str, int]'
  },
  cpp: {
    'int': 'int',
    'long': 'long long',
    'float': 'float',
    'double': 'double',
    'bool': 'bool',
    'string': 'string',
    'int[]': 'vector<int>',
    'long[]': 'vector<long long>',
    'float[]': 'vector<float>',
    'double[]': 'vector<double>',
    'bool[]': 'vector<bool>',
    'string[]': 'vector<string>',
    'List<int>': 'vector<int>',
    'List<long>': 'vector<long long>',
    'List<float>': 'vector<float>',
    'List<double>': 'vector<double>',
    'List<bool>': 'vector<bool>',
    'List<string>': 'vector<string>',
    'List<int[]>': 'vector<vector<int>>',
    'List<List<int>>': 'vector<vector<int>>',
    'Tree<int>': 'TreeNode*',
    'Tree<string>': 'TreeNode*',
    'Graph': 'vector<vector<int>>'
  },
  javascript: {
    'int': 'number',
    'long': 'number',
    'float': 'number',
    'double': 'number',
    'bool': 'boolean',
    'string': 'string',
    'int[]': 'number[]',
    'long[]': 'number[]',
    'float[]': 'number[]',
    'double[]': 'number[]',
    'bool[]': 'boolean[]',
    'string[]': 'string[]',
    'List<int>': 'number[]',
    'List<long>': 'number[]',
    'List<float>': 'number[]',
    'List<double>': 'number[]',
    'List<bool>': 'boolean[]',
    'List<string>': 'string[]',
    'List<int[]>': 'number[][]',
    'List<List<int>>': 'number[][]',
    'Tree<int>': 'TreeNode | null',
    'Tree<string>': 'TreeNode | null',
    'Graph': 'number[][]'
  }
};

module.exports = TYPE_MAPPINGS;